### ISSUE TITLE
مشکل دسترسی در پکیج AUR

### ISSUE THREAD

**Issue by nimafanniasl** [ekm507/araste#92]
سلام (:

تو پکیج aur آراسته، یه مشکلی با araste-get وجود داره، اونم اینه که نمیتونه فونت نصب یا حذف کنه :O

این ارور رو میده:

```[nima@laptop ~]$ araste-get install Six-Z
Downloading Font: Six-Z
Traceback (most recent call last):
  File "/usr/bin/araste-get", line 118, in <module>
    main()
  File "/usr/bin/araste-get", line 34, in main
    download_font(fonts_names, font_dir, repository=args.repository)
  File "/usr/bin/araste-get", line 98, in download_font
    with open(f"{font_dir}/{font}.aff", "wb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/araste/fonts/Six-Z.aff'
[nima@laptop ~]$ araste-get remove danial
Traceback (most recent call last):
  File "/usr/bin/araste-get", line 118, in <module>
    main()
  File "/usr/bin/araste-get", line 36, in main
    remove_font(fonts_names, font_dir)
  File "/usr/bin/araste-get", line 55, in remove_font
    os.remove(f"{font_dir}/{font}.aff")
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/araste/fonts/danial.aff'
```

نمیدونم چطور حلش کنم. شاید مشکل از این خط توی PKGBUILD باشه.

python setup.py install --prefix=/usr --root="${pkgdir}" --optimize=1

**Comment by ekm507** [comment]
خب طبق این خط:
```
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/araste/fonts/Six-Z.aff'
```
مشخصه که داره سعی می‌کنه قلم‌ها رو نه در مسیر ‎`~/.local`‬ بلکه در مسیر اصلی سیستم نصب کنه و خطای دسترسی می‌گیره.

دلیلش اینه که aur داره آراسته رو برای کل توزیع نصب می‌کنه.

یک بار با sudo امتحان کنید ببینید آیا دلیل مشکل همینه؟

البته استفاده از این دستور با sudo معقول نیست و باید مشکلش برطرف بشه که بتونه قلم‌ها رو در مسیر کاربر نصب کنه و آراسته هم باید بتونه قلم‌ها رو از همون مسیر برداره و استفاده کنه.

**Comment by nimafanniasl** [comment]
با تغییر prefix به ~/.local:

```
python setup.py install --prefix=~/.local --root="${pkgdir}" --optimize=1
```
زمان نصب این warning هارو میده:
‍‍
```
warning: directory permissions differ on /home/nima/
filesystem: 700  package: 755
warning: directory permissions differ on /home/nima/.local/
filesystem: 700  package: 755
```

و بعد نصب هم زمان نصب فونت این ارور:


```[nima@laptop araste-git]$ araste-get install Six-Z
Downloading Font: Six-Z
Traceback (most recent call last):
  File "/home/nima/.local/bin/araste-get", line 118, in <module>
    main()
  File "/home/nima/.local/bin/araste-get", line 34, in main
    download_font(fonts_names, font_dir, repository=args.repository)
  File "/home/nima/.local/bin/araste-get", line 98, in download_font
    with open(f"{font_dir}/{font}.aff", "wb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/nima/.local/lib/python3.11/site-packages/araste/fonts/Six-Z.aff'
```

**Comment by nimafanniasl** [comment]
با سودو هم میگه آراسته نصب نیست.
```
Error:
Araste is not installed
```
